application: codethechangeprojects
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: ctc/static
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /.*
  script: ctc.server.APP
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
